// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.2
// source: keymap/v1/editor.proto

/* eslint-disable */

export const protobufPackage = "keymap.v1";

/** EditorType represents the type of editor. */
export enum EditorType {
  /** EDITOR_TYPE_UNSPECIFIED - Unspecified */
  EDITOR_TYPE_UNSPECIFIED = 0,
  /**
   * VSCODE - VSCode series
   * Visual Studio Code
   */
  VSCODE = 1,
  /** WINDSURF - WindSurf */
  WINDSURF = 5,
  /** WINDSURF_NEXT - WindSurf preview */
  WINDSURF_NEXT = 6,
  /** CURSOR - Cursor */
  CURSOR = 7,
  /** ZED - Zed */
  ZED = 2,
  /**
   * INTELLIJ - IntelliJ series
   * IntelliJ IDEA Ultimate
   */
  INTELLIJ = 8,
  /** INTELLIJ_COMMUNITY - IntelliJ IDEA Community */
  INTELLIJ_COMMUNITY = 9,
  /** PYCHARM - PyCharm */
  PYCHARM = 10,
  /** WEBSTORM - WebStorm */
  WEBSTORM = 11,
  /** CLION - CLion */
  CLION = 12,
  /** PHPSTORM - PhpStorm */
  PHPSTORM = 13,
  /** RUBYMINE - RubyMine */
  RUBYMINE = 14,
  /** GOLAND - GoLand */
  GOLAND = 15,
  /** RUSTROVER - RustRover */
  RUSTROVER = 16,
  /** HELIX - Helix */
  HELIX = 3,
  /** VIM - Vim */
  VIM = 4,
  /** XCODE - Xcode */
  XCODE = 17,
  UNRECOGNIZED = -1,
}

export function editorTypeFromJSON(object: any): EditorType {
  switch (object) {
    case 0:
    case "EDITOR_TYPE_UNSPECIFIED":
      return EditorType.EDITOR_TYPE_UNSPECIFIED;
    case 1:
    case "VSCODE":
      return EditorType.VSCODE;
    case 5:
    case "WINDSURF":
      return EditorType.WINDSURF;
    case 6:
    case "WINDSURF_NEXT":
      return EditorType.WINDSURF_NEXT;
    case 7:
    case "CURSOR":
      return EditorType.CURSOR;
    case 2:
    case "ZED":
      return EditorType.ZED;
    case 8:
    case "INTELLIJ":
      return EditorType.INTELLIJ;
    case 9:
    case "INTELLIJ_COMMUNITY":
      return EditorType.INTELLIJ_COMMUNITY;
    case 10:
    case "PYCHARM":
      return EditorType.PYCHARM;
    case 11:
    case "WEBSTORM":
      return EditorType.WEBSTORM;
    case 12:
    case "CLION":
      return EditorType.CLION;
    case 13:
    case "PHPSTORM":
      return EditorType.PHPSTORM;
    case 14:
    case "RUBYMINE":
      return EditorType.RUBYMINE;
    case 15:
    case "GOLAND":
      return EditorType.GOLAND;
    case 16:
    case "RUSTROVER":
      return EditorType.RUSTROVER;
    case 3:
    case "HELIX":
      return EditorType.HELIX;
    case 4:
    case "VIM":
      return EditorType.VIM;
    case 17:
    case "XCODE":
      return EditorType.XCODE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EditorType.UNRECOGNIZED;
  }
}

export function editorTypeToJSON(object: EditorType): string {
  switch (object) {
    case EditorType.EDITOR_TYPE_UNSPECIFIED:
      return "EDITOR_TYPE_UNSPECIFIED";
    case EditorType.VSCODE:
      return "VSCODE";
    case EditorType.WINDSURF:
      return "WINDSURF";
    case EditorType.WINDSURF_NEXT:
      return "WINDSURF_NEXT";
    case EditorType.CURSOR:
      return "CURSOR";
    case EditorType.ZED:
      return "ZED";
    case EditorType.INTELLIJ:
      return "INTELLIJ";
    case EditorType.INTELLIJ_COMMUNITY:
      return "INTELLIJ_COMMUNITY";
    case EditorType.PYCHARM:
      return "PYCHARM";
    case EditorType.WEBSTORM:
      return "WEBSTORM";
    case EditorType.CLION:
      return "CLION";
    case EditorType.PHPSTORM:
      return "PHPSTORM";
    case EditorType.RUBYMINE:
      return "RUBYMINE";
    case EditorType.GOLAND:
      return "GOLAND";
    case EditorType.RUSTROVER:
      return "RUSTROVER";
    case EditorType.HELIX:
      return "HELIX";
    case EditorType.VIM:
      return "VIM";
    case EditorType.XCODE:
      return "XCODE";
    case EditorType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
