// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.2
// source: keymap/v1/keycode.proto

/* eslint-disable */

export const protobufPackage = "keymap.v1";

/** KeyModifier represents modifier keys like Shift, Ctrl, Alt, Meta. */
export enum KeyModifier {
  /** KEY_MODIFIER_UNSPECIFIED - Unspecified */
  KEY_MODIFIER_UNSPECIFIED = 0,
  /** KEY_MODIFIER_SHIFT - Shift key */
  KEY_MODIFIER_SHIFT = 1,
  /** KEY_MODIFIER_CTRL - Ctrl key */
  KEY_MODIFIER_CTRL = 2,
  /** KEY_MODIFIER_ALT - Alt key */
  KEY_MODIFIER_ALT = 3,
  /** KEY_MODIFIER_META - Meta is Command(⌘) key on macOS, Windows(⊞) key on Windows, super key on Linux */
  KEY_MODIFIER_META = 4,
  UNRECOGNIZED = -1,
}

export function keyModifierFromJSON(object: any): KeyModifier {
  switch (object) {
    case 0:
    case "KEY_MODIFIER_UNSPECIFIED":
      return KeyModifier.KEY_MODIFIER_UNSPECIFIED;
    case 1:
    case "KEY_MODIFIER_SHIFT":
      return KeyModifier.KEY_MODIFIER_SHIFT;
    case 2:
    case "KEY_MODIFIER_CTRL":
      return KeyModifier.KEY_MODIFIER_CTRL;
    case 3:
    case "KEY_MODIFIER_ALT":
      return KeyModifier.KEY_MODIFIER_ALT;
    case 4:
    case "KEY_MODIFIER_META":
      return KeyModifier.KEY_MODIFIER_META;
    case -1:
    case "UNRECOGNIZED":
    default:
      return KeyModifier.UNRECOGNIZED;
  }
}

export function keyModifierToJSON(object: KeyModifier): string {
  switch (object) {
    case KeyModifier.KEY_MODIFIER_UNSPECIFIED:
      return "KEY_MODIFIER_UNSPECIFIED";
    case KeyModifier.KEY_MODIFIER_SHIFT:
      return "KEY_MODIFIER_SHIFT";
    case KeyModifier.KEY_MODIFIER_CTRL:
      return "KEY_MODIFIER_CTRL";
    case KeyModifier.KEY_MODIFIER_ALT:
      return "KEY_MODIFIER_ALT";
    case KeyModifier.KEY_MODIFIER_META:
      return "KEY_MODIFIER_META";
    case KeyModifier.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * KeyCode represents a standard key code.
 * https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf page 53 show keyboard
 */
export enum KeyCode {
  /** KEY_CODE_UNSPECIFIED - Unspecified key code. */
  KEY_CODE_UNSPECIFIED = 0,
  /**
   * A - Letters
   * The 'A' key.
   */
  A = 1,
  /** B - The 'B' key. */
  B = 2,
  /** C - The 'C' key. */
  C = 3,
  /** D - The 'D' key. */
  D = 4,
  /** E - The 'E' key. */
  E = 5,
  /** F - The 'F' key. */
  F = 6,
  /** G - The 'G' key. */
  G = 7,
  /** H - The 'H' key. */
  H = 8,
  /** I - The 'I' key. */
  I = 9,
  /** J - The 'J' key. */
  J = 10,
  /** K - The 'K' key. */
  K = 11,
  /** L - The 'L' key. */
  L = 12,
  /** M - The 'M' key. */
  M = 13,
  /** N - The 'N' key. */
  N = 14,
  /** O - The 'O' key. */
  O = 15,
  /** P - The 'P' key. */
  P = 16,
  /** Q - The 'Q' key. */
  Q = 17,
  /** R - The 'R' key. */
  R = 18,
  /** S - The 'S' key. */
  S = 19,
  /** T - The 'T' key. */
  T = 20,
  /** U - The 'U' key. */
  U = 21,
  /** V - The 'V' key. */
  V = 22,
  /** W - The 'W' key. */
  W = 23,
  /** X - The 'X' key. */
  X = 24,
  /** Y - The 'Y' key. */
  Y = 25,
  /** Z - The 'Z' key. */
  Z = 26,
  /**
   * DIGIT_0 - Numbers
   * The '0' key on the main keyboard.
   */
  DIGIT_0 = 27,
  /** DIGIT_1 - The '1' key on the main keyboard. */
  DIGIT_1 = 28,
  /** DIGIT_2 - The '2' key on the main keyboard. */
  DIGIT_2 = 29,
  /** DIGIT_3 - The '3' key on the main keyboard. */
  DIGIT_3 = 30,
  /** DIGIT_4 - The '4' key on the main keyboard. */
  DIGIT_4 = 31,
  /** DIGIT_5 - The '5' key on the main keyboard. */
  DIGIT_5 = 32,
  /** DIGIT_6 - The '6' key on the main keyboard. */
  DIGIT_6 = 33,
  /** DIGIT_7 - The '7' key on the main keyboard. */
  DIGIT_7 = 34,
  /** DIGIT_8 - The '8' key on the main keyboard. */
  DIGIT_8 = 35,
  /** DIGIT_9 - The '9' key on the main keyboard. */
  DIGIT_9 = 36,
  /**
   * CAPS_LOCK - Modifiers
   * The Caps Lock key.
   */
  CAPS_LOCK = 40,
  /** SHIFT - The Shift key. */
  SHIFT = 41,
  /** FUNCTION - The Function key. */
  FUNCTION = 42,
  /** CONTROL - The Control key. */
  CONTROL = 43,
  /** OPTION - The Option (or Alt) key. */
  OPTION = 44,
  /** COMMAND - The Command key. */
  COMMAND = 45,
  /** RIGHT_COMMAND - The right Command key. */
  RIGHT_COMMAND = 46,
  /** RIGHT_OPTION - The right Option (or Alt) key. */
  RIGHT_OPTION = 47,
  /** RIGHT_CONTROL - The right Control key. */
  RIGHT_CONTROL = 48,
  /** RIGHT_SHIFT - The right Shift key. */
  RIGHT_SHIFT = 49,
  /**
   * RETURN - Miscellaneous
   * The Return (or Enter) key.
   */
  RETURN = 50,
  /** BACKSLASH - The backslash key. */
  BACKSLASH = 51,
  /** BACKTICK - The backtick (or grave accent) key. */
  BACKTICK = 52,
  /** COMMA - The comma key. */
  COMMA = 53,
  /** EQUAL - The equal key. */
  EQUAL = 54,
  /** MINUS - The minus key. */
  MINUS = 55,
  /** PLUS - The plus key. */
  PLUS = 56,
  /** PERIOD - The period key. */
  PERIOD = 57,
  /** QUOTE - The quote key. */
  QUOTE = 58,
  /** SEMICOLON - The semicolon key. */
  SEMICOLON = 59,
  /** SLASH - The slash key. */
  SLASH = 60,
  /** SPACE - The spacebar. */
  SPACE = 61,
  /** TAB - The Tab key. */
  TAB = 62,
  /** LEFT_BRACKET - The left bracket key. */
  LEFT_BRACKET = 63,
  /** RIGHT_BRACKET - The right bracket key. */
  RIGHT_BRACKET = 64,
  /** PAGE_UP - The Page Up key. */
  PAGE_UP = 65,
  /** PAGE_DOWN - The Page Down key. */
  PAGE_DOWN = 66,
  /** HOME - The Home key. */
  HOME = 67,
  /** END - The End key. */
  END = 68,
  /** UP_ARROW - The up arrow key. */
  UP_ARROW = 69,
  /** RIGHT_ARROW - The right arrow key. */
  RIGHT_ARROW = 70,
  /** DOWN_ARROW - The down arrow key. */
  DOWN_ARROW = 71,
  /** LEFT_ARROW - The left arrow key. */
  LEFT_ARROW = 72,
  /** ESCAPE - The Escape key. */
  ESCAPE = 73,
  /** DELETE - The Delete (or Backspace) key. */
  DELETE = 74,
  /** FORWARD_DELETE - The forward delete key. */
  FORWARD_DELETE = 76,
  /** INSERT_OR_HELP - The Insert/Help(on Mac) key. */
  INSERT_OR_HELP = 77,
  /** MUTE - The Mute key. */
  MUTE = 78,
  /** VOLUME_UP - The Volume Up key. */
  VOLUME_UP = 79,
  /** VOLUME_DOWN - The Volume Down key. */
  VOLUME_DOWN = 80,
  /**
   * F1 - Function keys
   * The F1 key.
   */
  F1 = 90,
  /** F2 - The F2 key. */
  F2 = 91,
  /** F3 - The F3 key. */
  F3 = 92,
  /** F4 - The F4 key. */
  F4 = 93,
  /** F5 - The F5 key. */
  F5 = 94,
  /** F6 - The F6 key. */
  F6 = 95,
  /** F7 - The F7 key. */
  F7 = 96,
  /** F8 - The F8 key. */
  F8 = 97,
  /** F9 - The F9 key. */
  F9 = 98,
  /** F10 - The F10 key. */
  F10 = 99,
  /** F11 - The F11 key. */
  F11 = 100,
  /** F12 - The F12 key. */
  F12 = 101,
  /** F13 - The F13 key. */
  F13 = 102,
  /** F14 - The F14 key. */
  F14 = 103,
  /** F15 - The F15 key. */
  F15 = 104,
  /** F16 - The F16 key. */
  F16 = 105,
  /** F17 - The F17 key. */
  F17 = 106,
  /** F18 - The F18 key. */
  F18 = 107,
  /** F19 - The F19 key. */
  F19 = 108,
  /** F20 - The F20 key. */
  F20 = 109,
  /**
   * NUMPAD_0 - Numpad
   * The '0' key on the numeric keypad.
   */
  NUMPAD_0 = 120,
  /** NUMPAD_1 - The '1' key on the numeric keypad. */
  NUMPAD_1 = 121,
  /** NUMPAD_2 - The '2' key on the numeric keypad. */
  NUMPAD_2 = 122,
  /** NUMPAD_3 - The '3' key on the numeric keypad. */
  NUMPAD_3 = 123,
  /** NUMPAD_4 - The '4' key on the numeric keypad. */
  NUMPAD_4 = 124,
  /** NUMPAD_5 - The '5' key on the numeric keypad. */
  NUMPAD_5 = 125,
  /** NUMPAD_6 - The '6' key on the numeric keypad. */
  NUMPAD_6 = 126,
  /** NUMPAD_7 - The '7' key on the numeric keypad. */
  NUMPAD_7 = 127,
  /** NUMPAD_8 - The '8' key on the numeric keypad. */
  NUMPAD_8 = 128,
  /** NUMPAD_9 - The '9' key on the numeric keypad. */
  NUMPAD_9 = 129,
  /** NUMPAD_CLEAR - The Clear key on the numeric keypad. */
  NUMPAD_CLEAR = 130,
  /** NUMPAD_DECIMAL - The decimal point key on the numeric keypad. */
  NUMPAD_DECIMAL = 131,
  /** NUMPAD_DIVIDE - The divide key on the numeric keypad. */
  NUMPAD_DIVIDE = 132,
  /** NUMPAD_ENTER - The Enter key on the numeric keypad. */
  NUMPAD_ENTER = 133,
  /** NUMPAD_EQUALS - The equals key on the numeric keypad. */
  NUMPAD_EQUALS = 134,
  /** NUMPAD_MINUS - The minus key on the numeric keypad. */
  NUMPAD_MINUS = 135,
  /** NUMPAD_MULTIPLY - The multiply key on the numeric keypad. */
  NUMPAD_MULTIPLY = 136,
  /** NUMPAD_PLUS - The plus key on the numeric keypad. */
  NUMPAD_PLUS = 137,
  /** NUMPAD_INSERT - The insert key on the numeric keypad. */
  NUMPAD_INSERT = 138,
  UNRECOGNIZED = -1,
}

export function keyCodeFromJSON(object: any): KeyCode {
  switch (object) {
    case 0:
    case "KEY_CODE_UNSPECIFIED":
      return KeyCode.KEY_CODE_UNSPECIFIED;
    case 1:
    case "A":
      return KeyCode.A;
    case 2:
    case "B":
      return KeyCode.B;
    case 3:
    case "C":
      return KeyCode.C;
    case 4:
    case "D":
      return KeyCode.D;
    case 5:
    case "E":
      return KeyCode.E;
    case 6:
    case "F":
      return KeyCode.F;
    case 7:
    case "G":
      return KeyCode.G;
    case 8:
    case "H":
      return KeyCode.H;
    case 9:
    case "I":
      return KeyCode.I;
    case 10:
    case "J":
      return KeyCode.J;
    case 11:
    case "K":
      return KeyCode.K;
    case 12:
    case "L":
      return KeyCode.L;
    case 13:
    case "M":
      return KeyCode.M;
    case 14:
    case "N":
      return KeyCode.N;
    case 15:
    case "O":
      return KeyCode.O;
    case 16:
    case "P":
      return KeyCode.P;
    case 17:
    case "Q":
      return KeyCode.Q;
    case 18:
    case "R":
      return KeyCode.R;
    case 19:
    case "S":
      return KeyCode.S;
    case 20:
    case "T":
      return KeyCode.T;
    case 21:
    case "U":
      return KeyCode.U;
    case 22:
    case "V":
      return KeyCode.V;
    case 23:
    case "W":
      return KeyCode.W;
    case 24:
    case "X":
      return KeyCode.X;
    case 25:
    case "Y":
      return KeyCode.Y;
    case 26:
    case "Z":
      return KeyCode.Z;
    case 27:
    case "DIGIT_0":
      return KeyCode.DIGIT_0;
    case 28:
    case "DIGIT_1":
      return KeyCode.DIGIT_1;
    case 29:
    case "DIGIT_2":
      return KeyCode.DIGIT_2;
    case 30:
    case "DIGIT_3":
      return KeyCode.DIGIT_3;
    case 31:
    case "DIGIT_4":
      return KeyCode.DIGIT_4;
    case 32:
    case "DIGIT_5":
      return KeyCode.DIGIT_5;
    case 33:
    case "DIGIT_6":
      return KeyCode.DIGIT_6;
    case 34:
    case "DIGIT_7":
      return KeyCode.DIGIT_7;
    case 35:
    case "DIGIT_8":
      return KeyCode.DIGIT_8;
    case 36:
    case "DIGIT_9":
      return KeyCode.DIGIT_9;
    case 40:
    case "CAPS_LOCK":
      return KeyCode.CAPS_LOCK;
    case 41:
    case "SHIFT":
      return KeyCode.SHIFT;
    case 42:
    case "FUNCTION":
      return KeyCode.FUNCTION;
    case 43:
    case "CONTROL":
      return KeyCode.CONTROL;
    case 44:
    case "OPTION":
      return KeyCode.OPTION;
    case 45:
    case "COMMAND":
      return KeyCode.COMMAND;
    case 46:
    case "RIGHT_COMMAND":
      return KeyCode.RIGHT_COMMAND;
    case 47:
    case "RIGHT_OPTION":
      return KeyCode.RIGHT_OPTION;
    case 48:
    case "RIGHT_CONTROL":
      return KeyCode.RIGHT_CONTROL;
    case 49:
    case "RIGHT_SHIFT":
      return KeyCode.RIGHT_SHIFT;
    case 50:
    case "RETURN":
      return KeyCode.RETURN;
    case 51:
    case "BACKSLASH":
      return KeyCode.BACKSLASH;
    case 52:
    case "BACKTICK":
      return KeyCode.BACKTICK;
    case 53:
    case "COMMA":
      return KeyCode.COMMA;
    case 54:
    case "EQUAL":
      return KeyCode.EQUAL;
    case 55:
    case "MINUS":
      return KeyCode.MINUS;
    case 56:
    case "PLUS":
      return KeyCode.PLUS;
    case 57:
    case "PERIOD":
      return KeyCode.PERIOD;
    case 58:
    case "QUOTE":
      return KeyCode.QUOTE;
    case 59:
    case "SEMICOLON":
      return KeyCode.SEMICOLON;
    case 60:
    case "SLASH":
      return KeyCode.SLASH;
    case 61:
    case "SPACE":
      return KeyCode.SPACE;
    case 62:
    case "TAB":
      return KeyCode.TAB;
    case 63:
    case "LEFT_BRACKET":
      return KeyCode.LEFT_BRACKET;
    case 64:
    case "RIGHT_BRACKET":
      return KeyCode.RIGHT_BRACKET;
    case 65:
    case "PAGE_UP":
      return KeyCode.PAGE_UP;
    case 66:
    case "PAGE_DOWN":
      return KeyCode.PAGE_DOWN;
    case 67:
    case "HOME":
      return KeyCode.HOME;
    case 68:
    case "END":
      return KeyCode.END;
    case 69:
    case "UP_ARROW":
      return KeyCode.UP_ARROW;
    case 70:
    case "RIGHT_ARROW":
      return KeyCode.RIGHT_ARROW;
    case 71:
    case "DOWN_ARROW":
      return KeyCode.DOWN_ARROW;
    case 72:
    case "LEFT_ARROW":
      return KeyCode.LEFT_ARROW;
    case 73:
    case "ESCAPE":
      return KeyCode.ESCAPE;
    case 74:
    case "DELETE":
      return KeyCode.DELETE;
    case 76:
    case "FORWARD_DELETE":
      return KeyCode.FORWARD_DELETE;
    case 77:
    case "INSERT_OR_HELP":
      return KeyCode.INSERT_OR_HELP;
    case 78:
    case "MUTE":
      return KeyCode.MUTE;
    case 79:
    case "VOLUME_UP":
      return KeyCode.VOLUME_UP;
    case 80:
    case "VOLUME_DOWN":
      return KeyCode.VOLUME_DOWN;
    case 90:
    case "F1":
      return KeyCode.F1;
    case 91:
    case "F2":
      return KeyCode.F2;
    case 92:
    case "F3":
      return KeyCode.F3;
    case 93:
    case "F4":
      return KeyCode.F4;
    case 94:
    case "F5":
      return KeyCode.F5;
    case 95:
    case "F6":
      return KeyCode.F6;
    case 96:
    case "F7":
      return KeyCode.F7;
    case 97:
    case "F8":
      return KeyCode.F8;
    case 98:
    case "F9":
      return KeyCode.F9;
    case 99:
    case "F10":
      return KeyCode.F10;
    case 100:
    case "F11":
      return KeyCode.F11;
    case 101:
    case "F12":
      return KeyCode.F12;
    case 102:
    case "F13":
      return KeyCode.F13;
    case 103:
    case "F14":
      return KeyCode.F14;
    case 104:
    case "F15":
      return KeyCode.F15;
    case 105:
    case "F16":
      return KeyCode.F16;
    case 106:
    case "F17":
      return KeyCode.F17;
    case 107:
    case "F18":
      return KeyCode.F18;
    case 108:
    case "F19":
      return KeyCode.F19;
    case 109:
    case "F20":
      return KeyCode.F20;
    case 120:
    case "NUMPAD_0":
      return KeyCode.NUMPAD_0;
    case 121:
    case "NUMPAD_1":
      return KeyCode.NUMPAD_1;
    case 122:
    case "NUMPAD_2":
      return KeyCode.NUMPAD_2;
    case 123:
    case "NUMPAD_3":
      return KeyCode.NUMPAD_3;
    case 124:
    case "NUMPAD_4":
      return KeyCode.NUMPAD_4;
    case 125:
    case "NUMPAD_5":
      return KeyCode.NUMPAD_5;
    case 126:
    case "NUMPAD_6":
      return KeyCode.NUMPAD_6;
    case 127:
    case "NUMPAD_7":
      return KeyCode.NUMPAD_7;
    case 128:
    case "NUMPAD_8":
      return KeyCode.NUMPAD_8;
    case 129:
    case "NUMPAD_9":
      return KeyCode.NUMPAD_9;
    case 130:
    case "NUMPAD_CLEAR":
      return KeyCode.NUMPAD_CLEAR;
    case 131:
    case "NUMPAD_DECIMAL":
      return KeyCode.NUMPAD_DECIMAL;
    case 132:
    case "NUMPAD_DIVIDE":
      return KeyCode.NUMPAD_DIVIDE;
    case 133:
    case "NUMPAD_ENTER":
      return KeyCode.NUMPAD_ENTER;
    case 134:
    case "NUMPAD_EQUALS":
      return KeyCode.NUMPAD_EQUALS;
    case 135:
    case "NUMPAD_MINUS":
      return KeyCode.NUMPAD_MINUS;
    case 136:
    case "NUMPAD_MULTIPLY":
      return KeyCode.NUMPAD_MULTIPLY;
    case 137:
    case "NUMPAD_PLUS":
      return KeyCode.NUMPAD_PLUS;
    case 138:
    case "NUMPAD_INSERT":
      return KeyCode.NUMPAD_INSERT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return KeyCode.UNRECOGNIZED;
  }
}

export function keyCodeToJSON(object: KeyCode): string {
  switch (object) {
    case KeyCode.KEY_CODE_UNSPECIFIED:
      return "KEY_CODE_UNSPECIFIED";
    case KeyCode.A:
      return "A";
    case KeyCode.B:
      return "B";
    case KeyCode.C:
      return "C";
    case KeyCode.D:
      return "D";
    case KeyCode.E:
      return "E";
    case KeyCode.F:
      return "F";
    case KeyCode.G:
      return "G";
    case KeyCode.H:
      return "H";
    case KeyCode.I:
      return "I";
    case KeyCode.J:
      return "J";
    case KeyCode.K:
      return "K";
    case KeyCode.L:
      return "L";
    case KeyCode.M:
      return "M";
    case KeyCode.N:
      return "N";
    case KeyCode.O:
      return "O";
    case KeyCode.P:
      return "P";
    case KeyCode.Q:
      return "Q";
    case KeyCode.R:
      return "R";
    case KeyCode.S:
      return "S";
    case KeyCode.T:
      return "T";
    case KeyCode.U:
      return "U";
    case KeyCode.V:
      return "V";
    case KeyCode.W:
      return "W";
    case KeyCode.X:
      return "X";
    case KeyCode.Y:
      return "Y";
    case KeyCode.Z:
      return "Z";
    case KeyCode.DIGIT_0:
      return "DIGIT_0";
    case KeyCode.DIGIT_1:
      return "DIGIT_1";
    case KeyCode.DIGIT_2:
      return "DIGIT_2";
    case KeyCode.DIGIT_3:
      return "DIGIT_3";
    case KeyCode.DIGIT_4:
      return "DIGIT_4";
    case KeyCode.DIGIT_5:
      return "DIGIT_5";
    case KeyCode.DIGIT_6:
      return "DIGIT_6";
    case KeyCode.DIGIT_7:
      return "DIGIT_7";
    case KeyCode.DIGIT_8:
      return "DIGIT_8";
    case KeyCode.DIGIT_9:
      return "DIGIT_9";
    case KeyCode.CAPS_LOCK:
      return "CAPS_LOCK";
    case KeyCode.SHIFT:
      return "SHIFT";
    case KeyCode.FUNCTION:
      return "FUNCTION";
    case KeyCode.CONTROL:
      return "CONTROL";
    case KeyCode.OPTION:
      return "OPTION";
    case KeyCode.COMMAND:
      return "COMMAND";
    case KeyCode.RIGHT_COMMAND:
      return "RIGHT_COMMAND";
    case KeyCode.RIGHT_OPTION:
      return "RIGHT_OPTION";
    case KeyCode.RIGHT_CONTROL:
      return "RIGHT_CONTROL";
    case KeyCode.RIGHT_SHIFT:
      return "RIGHT_SHIFT";
    case KeyCode.RETURN:
      return "RETURN";
    case KeyCode.BACKSLASH:
      return "BACKSLASH";
    case KeyCode.BACKTICK:
      return "BACKTICK";
    case KeyCode.COMMA:
      return "COMMA";
    case KeyCode.EQUAL:
      return "EQUAL";
    case KeyCode.MINUS:
      return "MINUS";
    case KeyCode.PLUS:
      return "PLUS";
    case KeyCode.PERIOD:
      return "PERIOD";
    case KeyCode.QUOTE:
      return "QUOTE";
    case KeyCode.SEMICOLON:
      return "SEMICOLON";
    case KeyCode.SLASH:
      return "SLASH";
    case KeyCode.SPACE:
      return "SPACE";
    case KeyCode.TAB:
      return "TAB";
    case KeyCode.LEFT_BRACKET:
      return "LEFT_BRACKET";
    case KeyCode.RIGHT_BRACKET:
      return "RIGHT_BRACKET";
    case KeyCode.PAGE_UP:
      return "PAGE_UP";
    case KeyCode.PAGE_DOWN:
      return "PAGE_DOWN";
    case KeyCode.HOME:
      return "HOME";
    case KeyCode.END:
      return "END";
    case KeyCode.UP_ARROW:
      return "UP_ARROW";
    case KeyCode.RIGHT_ARROW:
      return "RIGHT_ARROW";
    case KeyCode.DOWN_ARROW:
      return "DOWN_ARROW";
    case KeyCode.LEFT_ARROW:
      return "LEFT_ARROW";
    case KeyCode.ESCAPE:
      return "ESCAPE";
    case KeyCode.DELETE:
      return "DELETE";
    case KeyCode.FORWARD_DELETE:
      return "FORWARD_DELETE";
    case KeyCode.INSERT_OR_HELP:
      return "INSERT_OR_HELP";
    case KeyCode.MUTE:
      return "MUTE";
    case KeyCode.VOLUME_UP:
      return "VOLUME_UP";
    case KeyCode.VOLUME_DOWN:
      return "VOLUME_DOWN";
    case KeyCode.F1:
      return "F1";
    case KeyCode.F2:
      return "F2";
    case KeyCode.F3:
      return "F3";
    case KeyCode.F4:
      return "F4";
    case KeyCode.F5:
      return "F5";
    case KeyCode.F6:
      return "F6";
    case KeyCode.F7:
      return "F7";
    case KeyCode.F8:
      return "F8";
    case KeyCode.F9:
      return "F9";
    case KeyCode.F10:
      return "F10";
    case KeyCode.F11:
      return "F11";
    case KeyCode.F12:
      return "F12";
    case KeyCode.F13:
      return "F13";
    case KeyCode.F14:
      return "F14";
    case KeyCode.F15:
      return "F15";
    case KeyCode.F16:
      return "F16";
    case KeyCode.F17:
      return "F17";
    case KeyCode.F18:
      return "F18";
    case KeyCode.F19:
      return "F19";
    case KeyCode.F20:
      return "F20";
    case KeyCode.NUMPAD_0:
      return "NUMPAD_0";
    case KeyCode.NUMPAD_1:
      return "NUMPAD_1";
    case KeyCode.NUMPAD_2:
      return "NUMPAD_2";
    case KeyCode.NUMPAD_3:
      return "NUMPAD_3";
    case KeyCode.NUMPAD_4:
      return "NUMPAD_4";
    case KeyCode.NUMPAD_5:
      return "NUMPAD_5";
    case KeyCode.NUMPAD_6:
      return "NUMPAD_6";
    case KeyCode.NUMPAD_7:
      return "NUMPAD_7";
    case KeyCode.NUMPAD_8:
      return "NUMPAD_8";
    case KeyCode.NUMPAD_9:
      return "NUMPAD_9";
    case KeyCode.NUMPAD_CLEAR:
      return "NUMPAD_CLEAR";
    case KeyCode.NUMPAD_DECIMAL:
      return "NUMPAD_DECIMAL";
    case KeyCode.NUMPAD_DIVIDE:
      return "NUMPAD_DIVIDE";
    case KeyCode.NUMPAD_ENTER:
      return "NUMPAD_ENTER";
    case KeyCode.NUMPAD_EQUALS:
      return "NUMPAD_EQUALS";
    case KeyCode.NUMPAD_MINUS:
      return "NUMPAD_MINUS";
    case KeyCode.NUMPAD_MULTIPLY:
      return "NUMPAD_MULTIPLY";
    case KeyCode.NUMPAD_PLUS:
      return "NUMPAD_PLUS";
    case KeyCode.NUMPAD_INSERT:
      return "NUMPAD_INSERT";
    case KeyCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
