// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: keymap/v1/keymap.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { EditorType, editorTypeFromJSON, editorTypeToJSON } from "./editor";
import {
  KeyCode,
  keyCodeFromJSON,
  keyCodeToJSON,
  KeyModifier,
  keyModifierFromJSON,
  keyModifierToJSON,
} from "./keycode";

export const protobufPackage = "keymap.v1";

/** Keymap is the root message, representing a complete set of keybindings. */
export interface Keymap {
  /** Keymap name should follow "users/{user}/keymaps/{keymap}" pattern, e.g. users/1234/keymaps/1 */
  name: string;
  /**
   * (-- api-linter: core::0122::embedded-resource=disabled
   *     aip.dev/not-precedent: Action is a value object, not a separately managed resource --)
   * The actions.
   * One action may correspond to multiple keybindings. Then there would be multiple Action
   * with the same keybinding but different id.
   * Clients should merge Action that share the same `id` if necessary.
   */
  actions: Action[];
}

/** Action represents a single mapping from multiple key bindings to a logical action. */
export interface Action {
  /** Action name should follow "keymap/{keymap}/action/{name}" pattern, e.g. keymap/1/action/actions.editor.copy */
  name: string;
  /**
   * The key bindings that trigger the action.
   * e.g. ctrl+s, ctrl+shift+s
   */
  bindings: KeybindingReadable[];
  /** The action config */
  actionConfig:
    | ActionConfig
    | undefined;
  /** Optional, user-provided comment for this keymap. */
  comment: string;
}

/** KeyChord represents a combination of a primary key and optional modifiers. e.g. "ctrl+s" */
export interface KeyChord {
  /** The primary, non-modifier key being pressed. */
  keyCode: KeyCode;
  /** A list of modifier keys held down with the primary key. */
  modifiers: KeyModifier[];
}

/**
 * Keybinding represents a sequence of one or more key chords that must be
 * pressed in order to trigger an action. This allows for multi-key sequences
 * like "shift shift" or "ctrl+k ctrl+s".
 */
export interface Keybinding {
  /** The sequence of key chords. */
  chords: KeyChord[];
}

/** KeybindingReadable represents a single keybinding with its readable string */
export interface KeybindingReadable {
  /** The key binding that triggers an action. */
  keyChords:
    | Keybinding
    | undefined;
  /** The readable key binding that triggers an action. e.g. "ctrl+s" */
  keyChordsReadable: string;
}

/** ActionConfig represents the configuration of an action. */
export interface ActionConfig {
  /** name of the action */
  displayName: string;
  /** description of the action */
  description: string;
  /**
   * category of the action
   * e.g. "Editor", "Terminal"
   * Has subcategories if category has ".", e.g. "Editor.Clipboard"
   */
  category: string;
  /** editor support information for this action */
  editorSupport: EditorSupport[];
  /** children action ids */
  children: string[];
}

/** EditorSupport represents whether an action is supported by a specific editor. */
export interface EditorSupport {
  /** The editor type */
  editorType: EditorType;
  /** Whether this action is supported by the editor */
  supported: boolean;
  /** Special note of why not supported or supportness */
  note: string;
}

function createBaseKeymap(): Keymap {
  return { name: "", actions: [] };
}

export const Keymap: MessageFns<Keymap> = {
  encode(message: Keymap, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.actions) {
      Action.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Keymap {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeymap();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.actions.push(Action.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Keymap {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      actions: globalThis.Array.isArray(object?.actions) ? object.actions.map((e: any) => Action.fromJSON(e)) : [],
    };
  },

  toJSON(message: Keymap): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.actions?.length) {
      obj.actions = message.actions.map((e) => Action.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Keymap>, I>>(base?: I): Keymap {
    return Keymap.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Keymap>, I>>(object: I): Keymap {
    const message = createBaseKeymap();
    message.name = object.name ?? "";
    message.actions = object.actions?.map((e) => Action.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAction(): Action {
  return { name: "", bindings: [], actionConfig: undefined, comment: "" };
}

export const Action: MessageFns<Action> = {
  encode(message: Action, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.bindings) {
      KeybindingReadable.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.actionConfig !== undefined) {
      ActionConfig.encode(message.actionConfig, writer.uint32(26).fork()).join();
    }
    if (message.comment !== "") {
      writer.uint32(34).string(message.comment);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Action {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bindings.push(KeybindingReadable.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionConfig = ActionConfig.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.comment = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Action {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      bindings: globalThis.Array.isArray(object?.bindings)
        ? object.bindings.map((e: any) => KeybindingReadable.fromJSON(e))
        : [],
      actionConfig: isSet(object.actionConfig)
        ? ActionConfig.fromJSON(object.actionConfig)
        : isSet(object.action_config)
        ? ActionConfig.fromJSON(object.action_config)
        : undefined,
      comment: isSet(object.comment) ? globalThis.String(object.comment) : "",
    };
  },

  toJSON(message: Action): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.bindings?.length) {
      obj.bindings = message.bindings.map((e) => KeybindingReadable.toJSON(e));
    }
    if (message.actionConfig !== undefined) {
      obj.actionConfig = ActionConfig.toJSON(message.actionConfig);
    }
    if (message.comment !== "") {
      obj.comment = message.comment;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Action>, I>>(base?: I): Action {
    return Action.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Action>, I>>(object: I): Action {
    const message = createBaseAction();
    message.name = object.name ?? "";
    message.bindings = object.bindings?.map((e) => KeybindingReadable.fromPartial(e)) || [];
    message.actionConfig = (object.actionConfig !== undefined && object.actionConfig !== null)
      ? ActionConfig.fromPartial(object.actionConfig)
      : undefined;
    message.comment = object.comment ?? "";
    return message;
  },
};

function createBaseKeyChord(): KeyChord {
  return { keyCode: 0, modifiers: [] };
}

export const KeyChord: MessageFns<KeyChord> = {
  encode(message: KeyChord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.keyCode !== 0) {
      writer.uint32(8).int32(message.keyCode);
    }
    writer.uint32(18).fork();
    for (const v of message.modifiers) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyChord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyChord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.keyCode = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.modifiers.push(reader.int32() as any);

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.modifiers.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyChord {
    return {
      keyCode: isSet(object.keyCode)
        ? keyCodeFromJSON(object.keyCode)
        : isSet(object.key_code)
        ? keyCodeFromJSON(object.key_code)
        : 0,
      modifiers: globalThis.Array.isArray(object?.modifiers)
        ? object.modifiers.map((e: any) => keyModifierFromJSON(e))
        : [],
    };
  },

  toJSON(message: KeyChord): unknown {
    const obj: any = {};
    if (message.keyCode !== 0) {
      obj.keyCode = keyCodeToJSON(message.keyCode);
    }
    if (message.modifiers?.length) {
      obj.modifiers = message.modifiers.map((e) => keyModifierToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyChord>, I>>(base?: I): KeyChord {
    return KeyChord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyChord>, I>>(object: I): KeyChord {
    const message = createBaseKeyChord();
    message.keyCode = object.keyCode ?? 0;
    message.modifiers = object.modifiers?.map((e) => e) || [];
    return message;
  },
};

function createBaseKeybinding(): Keybinding {
  return { chords: [] };
}

export const Keybinding: MessageFns<Keybinding> = {
  encode(message: Keybinding, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.chords) {
      KeyChord.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Keybinding {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeybinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chords.push(KeyChord.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Keybinding {
    return {
      chords: globalThis.Array.isArray(object?.chords) ? object.chords.map((e: any) => KeyChord.fromJSON(e)) : [],
    };
  },

  toJSON(message: Keybinding): unknown {
    const obj: any = {};
    if (message.chords?.length) {
      obj.chords = message.chords.map((e) => KeyChord.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Keybinding>, I>>(base?: I): Keybinding {
    return Keybinding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Keybinding>, I>>(object: I): Keybinding {
    const message = createBaseKeybinding();
    message.chords = object.chords?.map((e) => KeyChord.fromPartial(e)) || [];
    return message;
  },
};

function createBaseKeybindingReadable(): KeybindingReadable {
  return { keyChords: undefined, keyChordsReadable: "" };
}

export const KeybindingReadable: MessageFns<KeybindingReadable> = {
  encode(message: KeybindingReadable, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.keyChords !== undefined) {
      Keybinding.encode(message.keyChords, writer.uint32(10).fork()).join();
    }
    if (message.keyChordsReadable !== "") {
      writer.uint32(18).string(message.keyChordsReadable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeybindingReadable {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeybindingReadable();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.keyChords = Keybinding.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.keyChordsReadable = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeybindingReadable {
    return {
      keyChords: isSet(object.keyChords)
        ? Keybinding.fromJSON(object.keyChords)
        : isSet(object.key_chords)
        ? Keybinding.fromJSON(object.key_chords)
        : undefined,
      keyChordsReadable: isSet(object.keyChordsReadable)
        ? globalThis.String(object.keyChordsReadable)
        : isSet(object.key_chords_readable)
        ? globalThis.String(object.key_chords_readable)
        : "",
    };
  },

  toJSON(message: KeybindingReadable): unknown {
    const obj: any = {};
    if (message.keyChords !== undefined) {
      obj.keyChords = Keybinding.toJSON(message.keyChords);
    }
    if (message.keyChordsReadable !== "") {
      obj.keyChordsReadable = message.keyChordsReadable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeybindingReadable>, I>>(base?: I): KeybindingReadable {
    return KeybindingReadable.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeybindingReadable>, I>>(object: I): KeybindingReadable {
    const message = createBaseKeybindingReadable();
    message.keyChords = (object.keyChords !== undefined && object.keyChords !== null)
      ? Keybinding.fromPartial(object.keyChords)
      : undefined;
    message.keyChordsReadable = object.keyChordsReadable ?? "";
    return message;
  },
};

function createBaseActionConfig(): ActionConfig {
  return { displayName: "", description: "", category: "", editorSupport: [], children: [] };
}

export const ActionConfig: MessageFns<ActionConfig> = {
  encode(message: ActionConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.displayName !== "") {
      writer.uint32(10).string(message.displayName);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.category !== "") {
      writer.uint32(26).string(message.category);
    }
    for (const v of message.editorSupport) {
      EditorSupport.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.children) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.editorSupport.push(EditorSupport.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.children.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionConfig {
    return {
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      editorSupport: globalThis.Array.isArray(object?.editorSupport)
        ? object.editorSupport.map((e: any) => EditorSupport.fromJSON(e))
        : globalThis.Array.isArray(object?.editor_support)
        ? object.editor_support.map((e: any) => EditorSupport.fromJSON(e))
        : [],
      children: globalThis.Array.isArray(object?.children) ? object.children.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: ActionConfig): unknown {
    const obj: any = {};
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.editorSupport?.length) {
      obj.editorSupport = message.editorSupport.map((e) => EditorSupport.toJSON(e));
    }
    if (message.children?.length) {
      obj.children = message.children;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionConfig>, I>>(base?: I): ActionConfig {
    return ActionConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionConfig>, I>>(object: I): ActionConfig {
    const message = createBaseActionConfig();
    message.displayName = object.displayName ?? "";
    message.description = object.description ?? "";
    message.category = object.category ?? "";
    message.editorSupport = object.editorSupport?.map((e) => EditorSupport.fromPartial(e)) || [];
    message.children = object.children?.map((e) => e) || [];
    return message;
  },
};

function createBaseEditorSupport(): EditorSupport {
  return { editorType: 0, supported: false, note: "" };
}

export const EditorSupport: MessageFns<EditorSupport> = {
  encode(message: EditorSupport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.editorType !== 0) {
      writer.uint32(8).int32(message.editorType);
    }
    if (message.supported !== false) {
      writer.uint32(16).bool(message.supported);
    }
    if (message.note !== "") {
      writer.uint32(26).string(message.note);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditorSupport {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditorSupport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.editorType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.supported = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.note = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EditorSupport {
    return {
      editorType: isSet(object.editorType)
        ? editorTypeFromJSON(object.editorType)
        : isSet(object.editor_type)
        ? editorTypeFromJSON(object.editor_type)
        : 0,
      supported: isSet(object.supported) ? globalThis.Boolean(object.supported) : false,
      note: isSet(object.note) ? globalThis.String(object.note) : "",
    };
  },

  toJSON(message: EditorSupport): unknown {
    const obj: any = {};
    if (message.editorType !== 0) {
      obj.editorType = editorTypeToJSON(message.editorType);
    }
    if (message.supported !== false) {
      obj.supported = message.supported;
    }
    if (message.note !== "") {
      obj.note = message.note;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EditorSupport>, I>>(base?: I): EditorSupport {
    return EditorSupport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EditorSupport>, I>>(object: I): EditorSupport {
    const message = createBaseEditorSupport();
    message.editorType = object.editorType ?? 0;
    message.supported = object.supported ?? false;
    message.note = object.note ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
