// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               unknown
// source: keymap/v1/platform.proto

/* eslint-disable */

export const protobufPackage = "keymap.v1";

/** Platform represents the platform type. */
export enum Platform {
  /** PLATFORM_UNSPECIFIED - Unspecified */
  PLATFORM_UNSPECIFIED = 0,
  /** MACOS - MacOS */
  MACOS = 1,
  /** WINDOWS - Windows, not support yet */
  WINDOWS = 2,
  /** LINUX - Linux, not support yet */
  LINUX = 3,
  UNRECOGNIZED = -1,
}

export function platformFromJSON(object: any): Platform {
  switch (object) {
    case 0:
    case "PLATFORM_UNSPECIFIED":
      return Platform.PLATFORM_UNSPECIFIED;
    case 1:
    case "MACOS":
      return Platform.MACOS;
    case 2:
    case "WINDOWS":
      return Platform.WINDOWS;
    case 3:
    case "LINUX":
      return Platform.LINUX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Platform.UNRECOGNIZED;
  }
}

export function platformToJSON(object: Platform): string {
  switch (object) {
    case Platform.PLATFORM_UNSPECIFIED:
      return "PLATFORM_UNSPECIFIED";
    case Platform.MACOS:
      return "MACOS";
    case Platform.WINDOWS:
      return "WINDOWS";
    case Platform.LINUX:
      return "LINUX";
    case Platform.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
